### PR TITLE
Error handling with anyhow crate

### PR DESCRIPTION
**Pull request by hniemeyer**
Example of error handling with anyhow.

### CODE REVIEW

**Comment by Lotterleben** [comment]
there's no real connection to be made to c++ similarities here, is there?

**Comment by hniemeyer** [comment]
> there's no real connection to be made to c++ similarities here, is there?

C++ exceptions look and work differently and not everyone is using them...

**Comment by Lotterleben** [comment]
oh absolutely– I was just wondering if there are some parallels to the way you can "append" context, bubble up without having to map errors etc.
Anyhow (hehe), I like this– when would we be discussing this? as an aside after we've done some hands-on error handling?

**Comment by hniemeyer** [comment]
> oh absolutely– I was just wondering if there are some parallels to the way you can "append" context, bubble up without having to map errors etc.
> Anyhow (hehe), I like this– when would we be discussing this? as an aside after we've done some hands-on error handling?

I think we can show this as an addon after the basic error handling,

**Pull request merged**
